### ISSUE TITLE
CLI: re-try nanopublication parse on a slight delay, to account for file system write issues

### ISSUE THREAD

**Issue by gordom6** [tetherless-world/twks#109]
Henrique Santos  5:51 PM
@Minor Gordon I’ve got this error in TWKS cli with a slightly different setting that I had before. In the DSA pipeline, the watch command is only started after the whole batch of initial nanopubs are loaded, so it captures the 9 initial nanopubs at once.
In this new setting, I started the watch command before loading the initial batch, so it captures the nanopubs one by one as they are loaded.
17:44:39.319 [main] INFO  e.r.t.t.c.c.WatchNanopublicationsCommand - directory change event: DirectoryChangeEvent{eventType=CREATE, path=/data/nanopublications/17487c86-4869-11ea-aae8-000c29f8c1cf/file, count=1}
17:44:39.320 [main] ERROR e.r.t.t.cli.CliNanopublicationParser - error parsing /data/nanopublications/17487c86-4869-11ea-aae8-000c29f8c1cf/file.twks.trig: 
edu.rpi.tw.twks.nanopub.MalformedNanopublicationException: no assertion statements
        at edu.rpi.tw.twks.nanopub.NanopublicationBuilder$NanopublicationAssertionBuilder.build(NanopublicationBuilder.java:87)
        at edu.rpi.tw.twks.nanopub.NanopublicationBuilder$NanopublicationAssertionBuilder.access$300(NanopublicationBuilder.java:81)
        at edu.rpi.tw.twks.nanopub.NanopublicationBuilder.build(NanopublicationBuilder.java:56)
        at edu.rpi.tw.twks.nanopub.NanopublicationParser.parseAll(NanopublicationParser.java:51)
        at edu.rpi.tw.twks.cli.CliNanopublicationParser.parseFile(CliNanopublicationParser.java:151)
        at edu.rpi.tw.twks.cli.CliNanopublicationParser.parseDirectory(CliNanopublicationParser.java:118)
        at edu.rpi.tw.twks.cli.command.WatchNanopublicationsCommand$NanopublicationsDirectoryWatcher.onEvent(WatchNanopublicationsCommand.java:115)
        at io.methvin.watcher.DirectoryWatcher.notifyCreateEvent(DirectoryWatcher.java:355)
        at io.methvin.watcher.DirectoryWatcher.lambda$watch$2(DirectoryWatcher.java:250)
        at io.methvin.watcher.PathUtils$1.visitFile(PathUtils.java:99)
        at io.methvin.watcher.PathUtils$1.visitFile(PathUtils.java:88)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at io.methvin.watcher.PathUtils.recursiveVisitFiles(PathUtils.java:86)
        at io.methvin.watcher.DirectoryWatcher.watch(DirectoryWatcher.java:247)
        at edu.rpi.tw.twks.cli.command.WatchNanopublicationsCommand$NanopublicationsDirectoryWatcher.watch(WatchNanopublicationsCommand.java:174)
        at edu.rpi.tw.twks.cli.command.WatchNanopublicationsCommand.run(WatchNanopublicationsCommand.java:66)
        at edu.rpi.tw.twks.cli.CliMain.main(CliMain.java:103)
It only happened once, so I think it may be related to the nanopub rewrite and how fast the next nanopub is written by whyis to the directory

**Comment by gordom6** [comment]
It's a timing issue. What's happening is: Depot is creating the file ("file"), then writing the contents. When the watcher sees the directory change event and tries to parse, the file contents haven't been written yet.

Depot should write to a temp file and then use atomic rename into the data/nanopublications directory, but since it's not, the TWKS CLI will have to accomodate that.

**Comment by gordom6** [comment]
Added two new command line options to watch and put, --retry (retry count, defaults to 0) and --retry-delay-s.
